### ISSUE TITLE
Fable version 3.2.*

### ISSUE THREAD

**Issue by kaashyapan** [fable-compiler/Fable.Store#10]
`/home/ubuntu/saturn-template/client/.fable/Fable.SvelteStore.1.0.0-beta-007/Fable.SvelteStore.fs(1,1): error EXCEPTION: Plugin SveltePlugins.DispatcherAttribute expects v3.1.15 but currently running Fable v3.2.12`

Is this restricted to a specific version ? Available in 3.1.* but missing in 3.2.*

**Comment by alfonsogarciacaro** [comment]
Hmm, this looks like a bug in the version resolution by Fable. It should be ok, because 3.2.* is higher than 3.1 but not a new major release. I will fix it in Fable and publish a new release of the compiler.

BTW, are you using Fable.SvelteStore just for testing or have you written an app with it? I'm asking because I haven't got much feedback of actual users of the library so I'm curious 😸

**Comment by kaashyapan** [comment]
I'm playing with it for now. Will keep you posted.
On a side note. I used your Feliz.Engine in https://github.com/plotly/Dash.NET/blob/dev/src/Dash.NET/Dash.NET.fsproj

Thanks for all your amazing work.

**Comment by alfonsogarciacaro** [comment]
That's great, thanks for letting me know! Credit goes to @Zaid-Ajaj for designing the great Feliz API for React. I'm happy that the Feliz.Engine abstraction is useful to you :)

BTW, can you please try to see if the plugin error is fixed with fable 3.2.14? You just need to run `dotnet tool update` before compilation.

Also, we're still experimenting, but if you're interested in using HTML for writing Fable apps you can also check [Fable.Lit](https://github.com/alfonsogarciacaro/Fable.Lit/).

**Comment by kaashyapan** [comment]
Yep. Works alright. Thanks.

I havent got around to playing with Fable.Lit yet. But will do.
I did play around with Feliz.Snabbdom. I was not able to use it because of some open issues with snabbdom.

I fanatically agree with your blog post about everything being observables. I have been using some of those ideas with Flutter mobile apps.
Will get back if I get stuck again / share if I manage to put together something useful.

**Comment by alfonsogarciacaro** [comment]
Thanks for confirming @kaashyapan!

Someone agrees with something I've written about architecture! That's a first ;) If you're interested in observables, you can also check [Sutil](https://sutil.dev/) which is an F#-only render library for Fable that's inspired by Svelte and uses the stores from this repo to manage the UI.
