### ISSUE TITLE
Make Store compatible with IObservable

### ISSUE THREAD

**Issue by AngelMunoz** [fable-compiler/Fable.Store#12]
From our discussion from here https://github.com/fable-compiler/Fable.Lit/discussions/44#discussioncomment-3304431 I think it could be a good idea to make the `Store` and `IStore` compatible with IObservable if you don't mind.

I can take this one but before I did I wanted to know if there are any particular issues or reasons on why is it not observable yet (besides time and hands maybe 😅 )

**Comment by alfonsogarciacaro** [comment]
`IStore` already inherits `IObservable` (plus `IDisposable`) and only adds the `Update` method: https://github.com/fable-compiler/Fable.Store/blob/992942a6fade6ae88ba498bf053ac3bfaa77e7fc/src/Fable.Store/Types.fs#L9-L12

The main difference is Stores should report immediately the current state upon subscription, but unfortunately we cannot express this guarantee with the type to maintain full compatibility with the `IObservable` interface: https://github.com/fable-compiler/Fable.Store/blob/992942a6fade6ae88ba498bf053ac3bfaa77e7fc/src/Fable.Store/Types.fs#L30-L35

Thanks to this, you can feed an `IStore` into an `Observable` chain (so you can filter, map, etc. the observable stream). The React adapter for example includes an `useObservable` version for the cases when you don't need the update function: https://github.com/fable-compiler/Fable.Store/blob/992942a6fade6ae88ba498bf053ac3bfaa77e7fc/src/Fable.ReactStore/Fable.ReactStore.fs#L42-L55

Would that be enough for your purposes or were you thinking in something else?

**Comment by AngelMunoz** [comment]
Oh my, I swear I did take a look and didn't see the inherit from observable then I'll start experimenting around it

I wanted to add a `Current` property as well, but I wanted to do the observable thing first, sorry for not noticing that! I don't know what I was looking at then 😔

**Comment by alfonsogarciacaro** [comment]
We had some discussions with @davedawkins about adding the `Current` property. If remember correctly, we opted for the "report immediately" guarantee instead because if you use the `Observable` module to make transformations, you get an `IObservable` instead, so you won't be able to access `Current`. But `Store.subscribeImmediate` will still work, that's why we opted to encourage this pattern instead: https://github.com/fable-compiler/Fable.Store/blob/992942a6fade6ae88ba498bf053ac3bfaa77e7fc/src/Fable.Store/Store.fs#L8-L17

**Comment by AngelMunoz** [comment]
that sounds reasonable and makes complete sense, thanks for the info!
