### ISSUE TITLE
Published Fable.Store 1.0.0-beta-002 has extra js file that throws off snowpack

### ISSUE THREAD

**Issue by johlrich** [fable-compiler/Fable.Store#7]
Fable.Store.fs.js in there with imports to sample pages.  `import { class_type } from "../../samples/FelizSvelte/src/.fable/fable-library.3.1.1/Reflection.js";`

I assume this was from an old build since there's no companion .fs file, but it threw off the way I had snowpack configured when it was walking the source.
 
Actually I just noticed all the nuget packages here seem to have the .fs.js files in the package with the imports to sample folder. These weren't causing issues since they have the .fs included which gets overwritten when running fable locally before snowpack tries to read them.

**Comment by MangelMaxime** [comment]
That's looks similar to an issue I raised only Feliz repo: https://github.com/Zaid-Ajaj/Feliz/issues/306

That's probably a file generated by Fable when compiling one of the sample.

We need to change the `*.fsproj` from:

```xml
<Content Include="*.fsproj; *.fs; *.js;" PackagePath="fable\" />
```

to

```fs
<Content Include="*.fsproj; *.fs;" PackagePath="fable\" />
```

because there is no local JavaScript in this project only F# files.

Maintainers needs to be more careful about their `fsproj` configuration now that Fable 3 genarates `*.fs.js` on place.

@johlrich In my case with Feliz, I was able to temporary have a workaround

> As a temporary work around, I delete manually the .fs.js file under the .fable folder and it appear that it force Fable to recompile it.

So in your case, it would means deleting the files in `.fable/Fable.Store/`

**Comment by alfonsogarciacaro** [comment]
Oh, my, you're right. I remember I saw the issue in Feliz repo but I forgot about that and copied the .fsproj files from some other place when creating this repo. Thanks a lot for the solution @MangelMaxime. I've republished the packages, could you please download the latest version and try again @johlrich?

**Comment by johlrich** [comment]
Everything good without arounds after update, thanks.
